
// ./commands/flux2.js

const axios = require('axios');

module.exports = {
    name: 'flux',
    aliases: ['fluximg', 'fluxai', 'aiflux', 'fluxpro'],
    category: 'ai',

    async execute({ sock, msg, args, jid }) {
        const prompt = args.join(' ');

        if (!prompt || prompt.trim().length < 3) {
            return sock.sendMessage(jid, {
                text:
                    '🎨 *Flux AI Image Generator*\n\n' +
                    '⚡ *Usage:*\n' +
                    '.flux <prompt>\n\n' +
                    '✨ *Examples:*\n' +
                    '.flux A handsome gentle man\n' +
                    '.flux Futuristic city at night\n' +
                    '.flux Cute cat in space\n' +
                    '.flux Beautiful sunset over mountains\n\n' +
                    '💡 Be descriptive for better results.',
                contextInfo: {
                    forwardingScore: 350,
                    isForwarded: true,
                    forwardedNewsletterMessageInfo: {
                        newsletterJid: '120363425394543602@newsletter',
                        newsletterName: '모🅒🅨🅑🅔🅡🅝🅞🅥🅐 🌟',
                        serverMessageId: 202,
                    },
                },
            }, { quoted: msg });
        }

        // ── Reaction ──
        try { await sock.sendMessage(jid, { react: { text: '🎨', key: msg.key } }); } catch (_) {}

        try {
            const encodedPrompt = encodeURIComponent(prompt);

            const { data } = await axios.get(
                `https://api.princetechn.com/api/ai/fluximg?apikey=prince&prompt=${encodedPrompt}`,
                { timeout: 90000 }
            );

            console.log('🎨 Flux2 Response:', JSON.stringify(data).substring(0, 300));

            // ── Extract image URL ──
            let imageUrl = null;

            // Format 1: data.result is a string (URL)
            if (typeof data?.result === 'string' && data.result.startsWith('http')) {
                imageUrl = data.result;
            }
            // Format 2: data.result.url
            else if (data?.result?.url && typeof data.result.url === 'string' && data.result.url.startsWith('http')) {
                imageUrl = data.result.url;
            }
            // Format 3: data.result.image_url
            else if (data?.result?.image_url && typeof data.result.image_url === 'string' && data.result.image_url.startsWith('http')) {
                imageUrl = data.result.image_url;
            }
            // Format 4: data.url
            else if (typeof data?.url === 'string' && data.url.startsWith('http')) {
                imageUrl = data.url;
            }
            // Format 5: data is a string
            else if (typeof data === 'string' && data.startsWith('http')) {
                imageUrl = data;
            }
            // Format 6: data.image_url
            else if (typeof data?.image_url === 'string' && data.image_url.startsWith('http')) {
                imageUrl = data.image_url;
            }

            if (!imageUrl) throw new Error('No image generated');

            // ── Send result ──
            let sent = false;

            try {
                await sock.sendMessage(jid, {
                    image: { url: imageUrl },
                    caption:
                        '🎨 *Flux AI*\n\n' +
                        `📝 *Prompt:* ${prompt.length > 200 ? prompt.substring(0, 200) + '...' : prompt}\n` +
                        `🔗 ${imageUrl}\n\n` +
                        '⚡ _Generated by Zenitsu_',
                    contextInfo: {
                        forwardingScore: 350,
                        isForwarded: true,
                        forwardedNewsletterMessageInfo: {
                            newsletterJid: '120363425394543602@newsletter',
                            newsletterName: '모🅒🅨🅑🅔🅡🅝🅞🅥🅐 🌟',
                            serverMessageId: 202,
                        },
                    },
                }, { quoted: msg });
                sent = true;
            } catch (imgErr) {
                console.log('⚠️ Flux image send failed:', imgErr.message);
            }

            // Fallback link
            if (!sent) {
                await sock.sendMessage(jid, {
                    text:
                        '🎨 *Flux AI*\n\n' +
                        `📝 *Prompt:* ${prompt}\n` +
                        `🔗 *Image:* ${imageUrl}\n\n` +
                        '⚠️ Sent as link.\n\n' +
                        '⚡ _Generated by Zenitsu Mini_',
                    contextInfo: {
                        forwardingScore: 350,
                        isForwarded: true,
                        forwardedNewsletterMessageInfo: {
                            newsletterJid: '120363425394543602@newsletter',
                            newsletterName: '모🅒🅨🅑🅔🅡🅝🅞🅥🅐 🌟',
                            serverMessageId: 202,
                        },
                    },
                }, { quoted: msg });
            }

            try { await sock.sendMessage(jid, { react: { text: '✅', key: msg.key } }); } catch (_) {}

        } catch (err) {
            console.error('❌ flux2 error:', err.message);
            try { await sock.sendMessage(jid, { react: { text: '❌', key: msg.key } }); } catch (_) {}

            await sock.sendMessage(jid, {
                text:
                    '❌ *Image Generation Failed*\n\n' +
                    'The AI service is currently unavailable.\n\n' +
                    '⚡ Try again in a few seconds with a different prompt.',
                contextInfo: {
                    forwardingScore: 350,
                    isForwarded: true,
                    forwardedNewsletterMessageInfo: {
                        newsletterJid: '120363425394543602@newsletter',
                        newsletterName: '모🅒🅨🅑🅔🅡🅝🅞🅥🅐 🌟',
                        serverMessageId: 202,
                    },
                },
            }, { quoted: msg });
        }
    },
};
