
// ./commands/veo.js

const axios = require('axios');

module.exports = {
    name: 'veo',
    aliases: ['aivideo', 'videogen'],
    category: 'ai',

    async execute({ sock, msg, args, jid }) {
        const prompt = args.join(' ');

        if (!prompt || prompt.trim().length < 3) {
            return sock.sendMessage(jid, {
                text:
                    '🎬 *Veo AI Video Generator*\n\n' +
                    '⚡ *Usage:*\n' +
                    '.veo <prompt>\n\n' +
                    '✨ *Examples:*\n' +
                    '.veo A cat playing piano\n' +
                    '.veo Sunset over ocean waves\n' +
                    '.veo Futuristic city at night',
                contextInfo: {
                    forwardingScore: 350,
                    isForwarded: true,
                    forwardedNewsletterMessageInfo: {
                        newsletterJid: '120363425394543602@newsletter',
                        newsletterName: '모🅒🅨🅑🅔🅡🅝🅞🅥🅐 🌟',
                        serverMessageId: 202,
                    },
                },
            }, { quoted: msg });
        }

        try { await sock.sendMessage(jid, { react: { text: '🎬', key: msg.key } }); } catch (_) {}

        try {
            const { data } = await axios.get(
                `https://api.giftedtech.co.ke/api/ai/veo3?apikey=gifted&prompt=${encodeURIComponent(prompt)}`,
                { timeout: 120000 }
            );

            let videoUrl = null;
            if (data?.result?.url) videoUrl = data.result.url;
            else if (data?.url) videoUrl = data.url;
            else if (data?.video_url) videoUrl = data.video_url;
            else if (typeof data === 'string' && data.startsWith('http')) videoUrl = data;

            if (!videoUrl) throw new Error('No video generated');

            // Send video
            await sock.sendMessage(jid, {
                video: { url: videoUrl },
                caption:
                    `🎬 *Veo AI*\n\n` +
                    `📝 *Prompt:* ${prompt}\n\n` +
                    `⚡ _Generated by Zenitsu_`,
                contextInfo: {
                    forwardingScore: 350,
                    isForwarded: true,
                    forwardedNewsletterMessageInfo: {
                        newsletterJid: '120363425394543602@newsletter',
                        newsletterName: '모🅒🅨🅑🅔🅡🅝🅞🅥🅐 🌟',
                        serverMessageId: 202,
                    },
                },
            }, { quoted: msg });

            try { await sock.sendMessage(jid, { react: { text: '✅', key: msg.key } }); } catch (_) {}

        } catch (err) {
            console.error('❌ veo error:', err.message);
            try { await sock.sendMessage(jid, { react: { text: '❌', key: msg.key } }); } catch (_) {}

            await sock.sendMessage(jid, {
                text: '❌ *Video Generation Failed*\n\nTry again with a different prompt.',
                contextInfo: {
                    forwardingScore: 350,
                    isForwarded: true,
                    forwardedNewsletterMessageInfo: {
                        newsletterJid: '120363425394543602@newsletter',
                        newsletterName: '모🅒🅨🅑🅔🅡🅝🅞🅥🅐 🌟',
                        serverMessageId: 202,
                    },
                },
            }, { quoted: msg });
        }
    },
};
